### ISSUE TITLE
Add some iframe methods 

### ISSUE THREAD

**Issue by VikasVashisth** [Zhui-CN/SeleniumFrame#1]
Can I make some contribution in this Repository related to iframe or Refresh methods in Java language of Selenium

**Comment by Zhui-CN** [comment]
> Can I make some contribution in this Repository related to iframe or Refresh methods in Java language of Selenium

Of course, I am also a beginner. How do I help you to join in the developer contribution?

**Comment by VikasVashisth** [comment]
I will raise a PR just merge into your branch. It will be beneficial for both of us.

**Comment by Zhui-CN** [comment]
> I will raise a PR just merge into your branch. It will be beneficial for both of us.

Okay, thanks, I read your code and found that it is for index, name, webElement to locate iframe, I think you can go to recursive iframe until found after the current frame can not find the element, you can not have to find the way to locate iframe.

**Comment by VikasVashisth** [comment]
Yes , I know this way also of recursion will add that too in upcoming PR.

**Comment by VikasVashisth** [comment]
Can ,I add one more contribution related to Refresh Methods in Selenium using Java language.
